AWSTemplateFormatVersion: '2010-09-09'
Description: Sets up a CloudFront distribution to serve item images from the S3 bucket with global edge caching. This distribution provides fast, secure, and reliable delivery of game item images to players worldwide, with HTTPS enforcement and optimized caching policies.

Parameters:
  ImagesBucketName:
    Type: String
    Description: Name of the S3 bucket containing images
  ImagesBucketArn:
    Type: String
    Description: ARN of the S3 bucket containing images
  DomainName:
    Type: String
    Description: Domain name for the CloudFront distribution
    Default: item-images.nathanpeck.gg
  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate
    Default: arn:aws:acm:us-east-1:784059518401:certificate/94e1f477-2af7-4f9a-a547-5f4ddd59474b

Resources:
  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub "${ImagesBucketArn}/*"
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'
              Bool:
                aws:SecureTransport: "true"

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "OAC for ${AWS::StackName}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-cf-logs-${AWS::AccountId}"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CloudFrontLoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudFrontLoggingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${CloudFrontLoggingBucket.Arn}/*"
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'
              Bool:
                aws:SecureTransport: "true"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: ItemImagesBucketOrigin
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
          MinTTL: 3600
          DefaultTTL: 86400
          MaxTTL: 31536000
          Compress: true
        Enabled: true
        HttpVersion: http3
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Logging:
          Bucket: !Sub "${CloudFrontLoggingBucket.DomainName}"
          Prefix: cf-logs/
          IncludeCookies: false
        Origins:
          - Id: ItemImagesBucketOrigin
            DomainName: !Sub '${ImagesBucketName}.s3.amazonaws.com'
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ''

Outputs:
  DistributionId:
    Description: ID of the CloudFront distribution
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionId"
  DistributionDomainName:
    Description: Domain name of the CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-DistributionDomainName"
  PlaceholderOutput:
    Description: Placeholder output value
    Value: "placeholder-cloudfront-distribution-value"

